<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserRegistrationTest extends TestCase
{
    use RefreshDatabase;
    // test whether name , email , password were given
    // test whether email is already used
    // check if the password and confirm_password
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->handleExceptions([QueryException::class]);
    }


    public function testNewUserMustProvideNecessaryFields()
    {
        $this->withExceptionHandling()
            ->withHeader('Accept' , 'application/json')
            ->json('post' , 'api/register' , ['name' => 'Sally'])
            ->assertStatus(422);
    }

}
